# default values
all:
  afAutomailerPlugin:
    delete_on_success: false
# if smtp definition is present - smtp delivery will be used - otherwise php's mail() function will be used
# port is optional
#    smtp:
#      host: some_host
#      port: 25
#      username: some_username
#      password: some_password
