propel:
  _attributes:    { package: plugins.afAutomailerPlugin.lib.model }
  
  ########################################################
  # - AUTOMAILER by radu --------------------------------#
  ########################################################
  af_automailer:
    _attributes:
      phpName: Automailer
      idMethod: native
    id:
      type: INTEGER
      required: 1
      autoIncrement: true
      primaryKey: true
    from_email:
      type: VARCHAR
      size: 255
      required: true
      default:
    from_name:
      type: VARCHAR
      size: 255
    to_email:
      type: VARCHAR
      size: 255
      required: true
      default:
    subject:
      type: LONGVARCHAR
      required: true
    body:
      type: LONGVARCHAR
      required: true
    alt_body:
      type: LONGVARCHAR
    sent_date:
      type: TIMESTAMP
    send_at_date:
      type: TIMESTAMP
      required: true
    is_sent:
      type: TINYINT
      required: true
      default: 0
    is_html:
      type: TINYINT
      required: true
      default: 0
    is_failed:
      type: TINYINT
      required: true
      default: 0
      